FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install express kafkajs mongoose && docker tag inventory-services raza17/inventory-services:latest

COPY . .

EXPOSE 3000

CMD ["node", "index.js"]