FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install express kafkajs mongoose axios && docker tag order-services raza17/order-services:latest

COPY . .

EXPOSE 3000

CMD ["node", "index.js"]