FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install express axios mongoose && docker tag payment-services raza17/payment-services:latest

COPY . .

EXPOSE 3000

CMD ["node", "index.js"]