FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install express kafkajs mongoose && docker tag customer-sevice raza17/customer-service:latest

COPY . .

EXPOSE 3000

CMD ["node", "index.js"]